### ISSUE TITLE
Gameplay

### ISSUE THREAD

**Issue by MinaroShikuchi** [MinaroShikuchi/mouton#5]
- [x] The game should end after a predefined number of seconds. 
- [x] The score of the game corresponds to the average number of sheep on the field.
- [ ] BONUS: Render the current score on the screen during the game

**Comment by NathanPo** [comment]
@MinaroShikuchi Tu sais s'il veut un écran de fin de jeu ? avec l'affichage du score ? ou on doit simplement le display dans le terminal ?

J'ai l'impression que l'étape 
> The game should end after a predefined number of seconds.

est déjà terminé ? quand on lance la commande ./SDL_Part1 10 10 100 les 100 secondes sont déjà coder

**Comment by MinaroShikuchi** [comment]
Yes ça c'est déjà fait. Si t'es chaud tu fais un menu still unity avec 
- play/resume
- restart
- exit
![Screenshot_20220131_122931_nz co codepoint minimetro](https://user-images.githubusercontent.com/45274627/151786308-5873b820-9914-4539-ad22-71218919239d.jpg)

**Comment by MinaroShikuchi** [comment]
Et pour le bonus si t'es chaud tu fais un petit overlay en gris avec un opacity 0.5 a peu près. tu met ça en haut à droite. Comme les compteurs de fps. 
Je pense il faut 
- temps restant, 
- nombre de loups
- nombre de mouton (en comptant ceux qui sont morts)

**Comment by NathanPo** [comment]
> Et pour le bonus si t'es chaud tu fais un petit overlay en gris avec un opacity 0.5 a peu près. tu met ça en haut à droite. Comme les compteurs de fps. Je pense il faut
> 
> * temps restant,
> * nombre de loups
> * nombre de mouton (en comptant ceux qui sont morts)

Ouais je vais essayer de rendre ça stylé

**Comment by NathanPo** [comment]
> Yes ça c'est déjà fait. Si t'es chaud tu fais un menu still unity avec
> 
> * play/resume
> * restart
> * exit
>   ![Screenshot_20220131_122931_nz co codepoint minimetro](https://user-images.githubusercontent.com/45274627/151786308-5873b820-9914-4539-ad22-71218919239d.jpg)

En revanche pour ça j’aime l’idée mais est-ce qu’il n’y aura pas une incohérence avec le cahier des charges ? On rentre un temps défini… et le fenêtre se ferme tu voudrais dire que tant qu’il n’a pas appuyé sur start le timer est bloquer etc ? Et à la fin du timer le jeu s’arrête ? Comme actuellement où on affiche le score et quitter ?
